export const ptcgSets = [
	{'id': 'base1', 'name': 'Base', 'ptcgoCode': 'BS'},
	{'id': 'base2', 'name': 'Jungle', 'ptcgoCode': 'JU'},
	{'id': 'basep', 'name': 'Wizards Black Star Promos', 'ptcgoCode': 'PR'},
	{'id': 'base3', 'name': 'Fossil', 'ptcgoCode': 'FO'},
	{'id': 'base4', 'name': 'Base Set 2', 'ptcgoCode': 'B2'},
	{'id': 'base5', 'name': 'Team Rocket', 'ptcgoCode': 'TR'},
	{'id': 'gym1', 'name': 'Gym Heroes', 'ptcgoCode': 'G1'},
	{'id': 'gym2', 'name': 'Gym Challenge', 'ptcgoCode': 'G2'},
	{'id': 'neo1', 'name': 'Neo Genesis', 'ptcgoCode': 'N1'},
	{'id': 'neo2', 'name': 'Neo Discovery', 'ptcgoCode': 'N2'},
	{'id': 'si1', 'name': 'Southern Islands'},
	{'id': 'neo3', 'name': 'Neo Revelation', 'ptcgoCode': 'N3'},
	{'id': 'neo4', 'name': 'Neo Destiny', 'ptcgoCode': 'N4'},
	{'id': 'base6', 'name': 'Legendary Collection', 'ptcgoCode': 'LC'},
	{'id': 'ecard1', 'name': 'Expedition Base Set', 'ptcgoCode': 'EX'},
	{'id': 'bp', 'name': 'Best of Game', 'ptcgoCode': 'BP'},
	{'id': 'ecard2', 'name': 'Aquapolis', 'ptcgoCode': 'AQ'},
	{'id': 'ecard3', 'name': 'Skyridge', 'ptcgoCode': 'SK'},
	{'id': 'ex1', 'name': 'Ruby & Sapphire', 'ptcgoCode': 'RS'},
	{'id': 'ex2', 'name': 'Sandstorm', 'ptcgoCode': 'SS'},
	{'id': 'np', 'name': 'Nintendo Black Star Promos', 'ptcgoCode': 'PR-NP'},
	{'id': 'ex3', 'name': 'Dragon', 'ptcgoCode': 'DR'},
	{'id': 'ex4', 'name': 'Team Magma vs Team Aqua', 'ptcgoCode': 'MA'},
	{'id': 'ex5', 'name': 'Hidden Legends', 'ptcgoCode': 'HL'},
	{'id': 'tk1a', 'name': 'EX Trainer Kit Latias'},
	{'id': 'tk1b', 'name': 'EX Trainer Kit Latios'},
	{'id': 'pop1', 'name': 'POP Series 1'},
	{'id': 'ex6', 'name': 'FireRed & LeafGreen', 'ptcgoCode': 'RG'},
	{'id': 'ex7', 'name': 'Team Rocket Returns', 'ptcgoCode': 'TRR'},
	{'id': 'ex8', 'name': 'Deoxys', 'ptcgoCode': 'DX'},
	{'id': 'ex9', 'name': 'Emerald', 'ptcgoCode': 'EM'},
	{'id': 'pop2', 'name': 'POP Series 2'},
	{'id': 'ex10', 'name': 'Unseen Forces', 'ptcgoCode': 'UF'},
	{'id': 'ex11', 'name': 'Delta Species', 'ptcgoCode': 'DS'},
	{'id': 'ex12', 'name': 'Legend Maker', 'ptcgoCode': 'LM'},
	{'id': 'tk2a', 'name': 'EX Trainer Kit 2 Plusle'},
	{'id': 'tk2b', 'name': 'EX Trainer Kit 2 Minun'},
	{'id': 'pop3', 'name': 'POP Series 3'},
	{'id': 'ex13', 'name': 'Holon Phantoms', 'ptcgoCode': 'HP'},
	{'id': 'pop4', 'name': 'POP Series 4'},
	{'id': 'ex14', 'name': 'Crystal Guardians', 'ptcgoCode': 'CG'},
	{'id': 'ex15', 'name': 'Dragon Frontiers', 'ptcgoCode': 'DF'},
	{'id': 'ex16', 'name': 'Power Keepers', 'ptcgoCode': 'PK'},
	{'id': 'pop5', 'name': 'POP Series 5'},
	{'id': 'dpp', 'name': 'DP Black Star Promos', 'ptcgoCode': 'PR-DPP', 'prefix': 'DP'},
	{'id': 'dp1', 'name': 'Diamond & Pearl', 'ptcgoCode': 'DP'},
	{'id': 'dp2', 'name': 'Mysterious Treasures', 'ptcgoCode': 'MT'},
	{'id': 'pop6', 'name': 'POP Series 6'},
	{'id': 'dp3', 'name': 'Secret Wonders', 'ptcgoCode': 'SW'},
	{'id': 'dp4', 'name': 'Great Encounters', 'ptcgoCode': 'GE'},
	{'id': 'pop7', 'name': 'POP Series 7'},
	{'id': 'dp5', 'name': 'Majestic Dawn', 'ptcgoCode': 'MD'},
	{'id': 'dp6', 'name': 'Legends Awakened', 'ptcgoCode': 'LA'},
	{'id': 'pop8', 'name': 'POP Series 8'},
	{'id': 'dp7', 'name': 'Stormfront', 'ptcgoCode': 'SF'},
	{'id': 'pl1', 'name': 'Platinum', 'ptcgoCode': 'PL'},
	{'id': 'pop9', 'name': 'POP Series 9'},
	{'id': 'pl2', 'name': 'Rising Rivals', 'ptcgoCode': 'RR'},
	{'id': 'pl3', 'name': 'Supreme Victors', 'ptcgoCode': 'SV'},
	{'id': 'pl4', 'name': 'Arceus', 'ptcgoCode': 'AR'},
	{'id': 'ru1', 'name': 'Pokémon Rumble'},
	{'id': 'hgss1', 'name': 'HeartGold & SoulSilver', 'ptcgoCode': 'HS'},
	{'id': 'hsp', 'name': 'HGSS Black Star Promos', 'ptcgoCode': 'PR-HS', 'prefix': 'HGSS'},
	{'id': 'hgss2', 'name': 'HS—Unleashed', 'ptcgoCode': 'UL'},
	{'id': 'hgss3', 'name': 'HS—Undaunted', 'ptcgoCode': 'UD'},
	{'id': 'hgss4', 'name': 'HS—Triumphant', 'ptcgoCode': 'TM'},
	{'id': 'col1', 'name': 'Call of Legends', 'ptcgoCode': 'CL'},
	{'id': 'bwp', 'name': 'BW Black Star Promos', 'ptcgoCode': 'PR-BLW', 'prefix': 'BW'},
	{'id': 'bw1', 'name': 'Black & White', 'ptcgoCode': 'BLW'},
	{'id': 'mcd11', 'name': "McDonald's Collection 2011"},
	{'id': 'bw2', 'name': 'Emerging Powers', 'ptcgoCode': 'EPO'},
	{'id': 'bw3', 'name': 'Noble Victories', 'ptcgoCode': 'NVI'},
	{'id': 'bw4', 'name': 'Next Destinies', 'ptcgoCode': 'NXD'},
	{'id': 'bw5', 'name': 'Dark Explorers', 'ptcgoCode': 'DEX'},
	{'id': 'mcd12', 'name': "McDonald's Collection 2012"},
	{'id': 'bw6', 'name': 'Dragons Exalted', 'ptcgoCode': 'DRX'},
	{'id': 'dv1', 'name': 'Dragon Vault', 'ptcgoCode': 'DRV'},
	{'id': 'bw7', 'name': 'Boundaries Crossed', 'ptcgoCode': 'BCR'},
	{'id': 'bw8', 'name': 'Plasma Storm', 'ptcgoCode': 'PLS'},
	{'id': 'bw9', 'name': 'Plasma Freeze', 'ptcgoCode': 'PLF'},
	{'id': 'bw10', 'name': 'Plasma Blast', 'ptcgoCode': 'PLB'},
	{'id': 'xyp', 'name': 'XY Black Star Promos', 'ptcgoCode': 'PR-XY', 'prefix': 'XY'},
	{'id': 'bw11', 'name': 'Legendary Treasures', 'ptcgoCode': 'LTR'},
	{'id': 'xy0', 'name': 'Kalos Starter Set', 'ptcgoCode': 'KSS'},
	{'id': 'xy1', 'name': 'XY', 'ptcgoCode': 'XY'},
	{'id': 'xy2', 'name': 'Flashfire', 'ptcgoCode': 'FLF'},
	{'id': 'mcd14', 'name': "McDonald's Collection 2014"},
	{'id': 'xy3', 'name': 'Furious Fists', 'ptcgoCode': 'FFI'},
	{'id': 'xy4', 'name': 'Phantom Forces', 'ptcgoCode': 'PHF'},
	{'id': 'xy5', 'name': 'Primal Clash', 'ptcgoCode': 'PRC'},
	{'id': 'dc1', 'name': 'Double Crisis', 'ptcgoCode': 'DCR'},
	{'id': 'xy6', 'name': 'Roaring Skies', 'ptcgoCode': 'ROS'},
	{'id': 'xy7', 'name': 'Ancient Origins', 'ptcgoCode': 'AOR'},
	{'id': 'xy8', 'name': 'BREAKthrough', 'ptcgoCode': 'BKT'},
	{'id': 'mcd15', 'name': "McDonald's Collection 2015"},
	{'id': 'xy9', 'name': 'BREAKpoint', 'ptcgoCode': 'BKP'},
	{'id': 'g1', 'name': 'Generations', 'ptcgoCode': 'GEN'},
	{'id': 'xy10', 'name': 'Fates Collide', 'ptcgoCode': 'FCO'},
	{'id': 'xy11', 'name': 'Steam Siege', 'ptcgoCode': 'STS'},
	{'id': 'mcd16', 'name': "McDonald's Collection 2016"},
	{'id': 'xy12', 'name': 'Evolutions', 'ptcgoCode': 'EVO'},
	{'id': 'smp', 'name': 'SM Black Star Promos', 'ptcgoCode': 'PR-SM', 'prefix': 'SM'},
	{'id': 'sm1', 'name': 'Sun & Moon', 'ptcgoCode': 'SUM'},
	{'id': 'sm2', 'name': 'Guardians Rising', 'ptcgoCode': 'GRI'},
	{'id': 'sm3', 'name': 'Burning Shadows', 'ptcgoCode': 'BUS'},
	{'id': 'sm35', 'name': 'Shining Legends', 'ptcgoCode': 'SLG'},
	{'id': 'sm4', 'name': 'Crimson Invasion', 'ptcgoCode': 'CIN'},
	{'id': 'mcd17', 'name': "McDonald's Collection 2017"},
	{'id': 'sm5', 'name': 'Ultra Prism', 'ptcgoCode': 'UPR'},
	{'id': 'sm6', 'name': 'Forbidden Light', 'ptcgoCode': 'FLI'},
	{'id': 'sm7', 'name': 'Celestial Storm', 'ptcgoCode': 'CES'},
	{'id': 'sm75', 'name': 'Dragon Majesty', 'ptcgoCode': 'DRM'},
	{'id': 'mcd18', 'name': "McDonald's Collection 2018"},
	{'id': 'sm8', 'name': 'Lost Thunder', 'ptcgoCode': 'LOT'},
	{'id': 'sm9', 'name': 'Team Up', 'ptcgoCode': 'TEU'},
	{'id': 'det1', 'name': 'Detective Pikachu', 'ptcgoCode': 'DET'},
	{'id': 'sm10', 'name': 'Unbroken Bonds', 'ptcgoCode': 'UNB'},
	{'id': 'sm11', 'name': 'Unified Minds', 'ptcgoCode': 'UNM'},
	{'id': 'sm115', 'name': 'Hidden Fates', 'ptcgoCode': 'HIF'},
	{'id': 'sma', 'name': 'Shiny Vault'},
	{'id': 'mcd19', 'name': "McDonald's Collection 2019"},
	{'id': 'sm12', 'name': 'Cosmic Eclipse', 'ptcgoCode': 'CEC'},
	{'id': 'swshp', 'name': 'SWSH Black Star Promos', 'ptcgoCode': 'PR-SW', 'prefix': 'SWSH'},
	{'id': 'swsh1', 'name': 'Sword & Shield', 'ptcgoCode': 'SSH'},
	{'id': 'swsh2', 'name': 'Rebel Clash', 'ptcgoCode': 'RCL'},
	{'id': 'swsh3', 'name': 'Darkness Ablaze', 'ptcgoCode': 'DAA'},
	{'id': 'fut20', 'name': 'Pokémon Futsal Collection', 'ptcgoCode': 'FUT20'},
	{'id': 'swsh35', 'name': "Champion's Path", 'ptcgoCode': 'CPA'},
	{'id': 'swsh4', 'name': 'Vivid Voltage', 'ptcgoCode': 'VIV'},
	{'id': 'mcd21', 'name': "McDonald's Collection 2021"},
	{'id': 'swsh45sv', 'name': 'Shiny Vault', 'ptcgoCode': 'SHF'},
	{'id': 'swsh45', 'name': 'Shining Fates', 'ptcgoCode': 'SHF'},
	{'id': 'swsh5', 'name': 'Battle Styles', 'ptcgoCode': 'BST'},
	{'id': 'swsh6', 'name': 'Chilling Reign', 'ptcgoCode': 'CRE'},
	{'id': 'swsh7', 'name': 'Evolving Skies', 'ptcgoCode': 'EVS'},
	// {'id': 'cel25c', 'name': 'Celebrations: Classic Collection', 'ptcgoCode': 'CEL'},
	{'id': 'cel25', 'name': 'Celebrations', 'ptcgoCode': 'CEL'},
	{'id': 'swsh8', 'name': 'Fusion Strike', 'ptcgoCode': 'FST'},
	{'id': 'swsh9', 'name': 'Brilliant Stars', 'ptcgoCode': 'BRS'},
	// {'id': 'swsh9tg', 'name': 'Brilliant Stars Trainer Gallery', 'ptcgoCode': 'BRS'},
	{'id': 'swsh10', 'name': 'Astral Radiance', 'ptcgoCode': 'ASR'},
	// {'id': 'swsh10tg', 'name': 'Astral Radiance Trainer Gallery', 'ptcgoCode': 'ASR'},
	{'id': 'pgo', 'name': 'Pokémon GO', 'ptcgoCode': 'PGO'},
	{'id': 'mcd22', 'name': "McDonald's Collection 2022"},
	// {'id': 'swsh11tg', 'name': 'Lost Origin Trainer Gallery', 'ptcgoCode': 'LOR'},
	{'id': 'swsh11', 'name': 'Lost Origin', 'ptcgoCode': 'LOR'},
	{'id': 'swsh12', 'name': 'Silver Tempest', 'ptcgoCode': 'SIT'},
	// {'id': 'swsh12tg', 'name': 'Silver Tempest Trainer Gallery', 'ptcgoCode': 'SIT'},
	{'id': 'svp', 'name': 'Scarlet & Violet Black Star Promos', 'ptcgoCode': 'PR-SV'},
	// {'id': 'swsh12pt5gg', 'name': 'Crown Zenith Galarian Gallery', 'ptcgoCode': 'CRZ'},
	{'id': 'swsh12pt5', 'name': 'Crown Zenith', 'ptcgoCode': 'CRZ'},
	{'id': 'sve', 'name': 'Scarlet & Violet Energies', 'ptcgoCode': 'SVE'},
	{'id': 'sve', 'name': 'Scarlet & Violet Energies', 'ptcgoCode': 'Energy'},
	{'id': 'sv1', 'name': 'Scarlet & Violet', 'ptcgoCode': 'SVI'},
	{'id': 'sv2', 'name': 'Paldea Evolved', 'ptcgoCode': 'PAL'},
	{'id': 'sv3', 'name': 'Obsidian Flames', 'ptcgoCode': 'OBF'},
	{'id': 'sv3pt5', 'name': '151', 'ptcgoCode': 'MEW'},
  {'id': 'sv4', 'name': 'Paradox Rift', 'ptcgoCode': 'PAR'},
  {'id': 'sv4pt5', 'name': 'Paldean Fates', 'ptcgoCode': 'PAF'},
  {'id': 'sv5', 'name': 'Temporal Forces', 'ptcgoCode': 'TEF'}
]